import type { Metadata } from 'next';
import './globals.scss';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import 'react-datepicker/dist/react-datepicker.css';

export const metadata: Metadata = {
    title: 'LINEMATE',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <meta charSet="utf-8" />
                <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=yes" />
                <meta name="robots" content="index,follow" />
                <meta name="theme-color" content="#000000" />
                <link rel="shortcut icon" href="/favicon.ico" />
                <meta property="og:url" content="https://www.linemate.kr" />
                <meta property="og:type" content="website" />
                <meta property="og:title" content="LINEMATE" />
                <meta property="og:description" content="라인메이트 입니다." />
                <meta property="og:image" content="" />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="630" />
                <meta name="twitter:card" content="summary" />
                <meta name="twitter:title" content="LINEMATE" />
                <meta name="twitter:description" content="" />
                <meta name="twitter:image" content="" />
                <meta httpEquiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
            </head>
            <body>
                <div className="linemate">{children}</div>
                <div id="modal"></div>
                <div id="popup"></div>
            </body>
        </html>
    );
}
